name: deploy

# PRがクローズされたときに動くように変更
on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  deploy:
    # no-deploy ラベルがあればデプロイをしない
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'no-deploy')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: echo 'check out ok'
      - name: deploy
        run: echo 'deploy ok'

