name: deploy

# PRがクローズされたときに動くように変更
on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: echo 'check out: ok'
      - name: deploy
        run: echo 'deploy: ok'

